package com.swapna.foodapp.utils

object TestConstants {
    const val USER_ID = "u1"
    const val USER_NAME = "Swapna"
    const val USER_EMAIL = "swapna@test.com"
    const val USER_PHONE = "+91 9876543210"
    const val ADDRESS_ID = "a1"
    const val ADDRESS_LABEL = "Home"
    const val FULL_ADDRESS = "123 MG Road, Koramangala, Bengaluru"
    const val LANDMARK = "Near Brigade Road"
    const val RESTAURANT_ID = "r1"
    const val RESTAURANT_NAME = "Meghana Foods"
    const val RESTAURANT_RATING = 4.6
    const val DELIVERY_TIME = 30
    const val RESTAURANT_ADDRESS = "5th Block, Koramangala, Bengaluru"
    const val SEARCH_ADDRESS = "5th Block, Koramangala, Bengaluru"
    const val LOCALITY = "Koramangala"
    const val IMAGE_URL = "https://example.com/image.jpg"
    const val THUMB_URL = "https://example.com/thumb.jpg"
    const val MENU_ID = "m1"
    const val MENU_NAME = "Chicken Biryani"
    const val MENU_PRICE = 249.0
    const val CATEGORY = "Biryani"
    const val DESCRIPTION = "Delicious Chicken Biryani"
    const val FOOD_IMAGE = "https://example.com/food.jpg"
    const val CART_ID = "c1"
    const val QUANTITY = 1
    const val OPTION_ID = "opt1"
    const val OPENING_HOURS_DEFAULT = "11 AM - 11 PM"
    const val FAKE_RESTAURANT_VOTES = 1000
    const val FAKE_OFFER_UPTO_100  = "50% off upto ₹100"
    const val CUSTOM_DEFAULT_ID = "custom_1"
    const val CUSTOM_OPT_LARGE_ID = "opt_large"
    const val OPTION_LABEL = "Regular"
    const val EXTRA_PRICE = 0.0
    const val ORDER_ID = "ord1"
    const val TOTAL_AMOUNT = 291.45
    const val FAKE_USER_EMAIL = "swapna@email.com"
    const val FAKE_USER_NAME = "Swapna Prakash"
    const val FAKE_USER_ID = "u_001"
        const val VALID_PHONE = "9876543210"
    const val VALID_OTP = "123456"
    const val PHONE_TOO_SHORT = "98765"
    const val PHONE_EMPTY = ""
    const val PHONE_WITH_LETTERS = "abc1234567"
    const val PHONE_TOO_LONG = "123456789012"
    const val OTP_TOO_SHORT = "1234"
    const val OTP_EMPTY = ""
    const val OTP_WRONG = "000000"
    const val OTP_WRONG_FIREBASE = "999999"
    const val ERR_NETWORK_UNAVAILABLE =
        "Network unavailable"
    const val ERR_WRONG_OTP_REPOSITORY =
        "Wrong OTP. Try again."
    const val ERR_WRONG_OTP_FIREBASE =
        "Wrong OTP. Please check and try again."
    const val ERR_APP_IN_BACKGROUND =
        "App is in background. Please reopen and try again."
    const val CART_ID_1 = "c1"
    const val CART_ID_2 = "c2"
    const val MENU_ID_1 = "m1"
    const val MENU_ID_2 = "m2"
    const val MENU_ID_3 = "m3"
    const val CART_QTY_1 = 1
    const val CART_QTY_2 = 2
    const val CART_QTY_3 = 3
    const val CART_QTY_5 = 5
    const val PRICE_249 = 249.0
    const val PRICE_50 = 50.0
    const val PRICE_100 = 100.0
    const val CUSTOMISATION_LARGE = "large"
    const val CUSTOMISATION_HOT = "hot"
    const val EXTRA_PRICE_LARGE = 50.0
    const val EXTRA_PRICE_ZERO = 0.0
    const val BASE_PRICE_249 = 249.0
    const val BASE_PRICE_199 = 199.0
    const val TOTAL_PRICE_598 = 598.0   // (249+50) × 2
    const val TOTAL_PRICE_747 = 747.0   // 249 × 3

    const val DB_ERROR_MSG = "Database error"
    const val QTY_ZERO = 0
    const val QTY_NEGATIVE = -1
    const val QTY_2 = 2
    const val QTY_3 = 3
    const val QTY_5 = 5
    const val QTY_9 = 9
    const val TEST_PRICE_BIRYANI = 249.0
    const val TEST_PRICE_PIZZA = 449.0
    const val TEST_PRICE_EXTRA = 80.0
    const val SUBTOTAL_TWO_ITEMS = 698.0   // 249 + 449
    const val SUBTOTAL_QTY3 = 747.0   // 249 × 3
    const val SUBTOTAL_WITH_EXTRA = 658.0   // (249+80) × 2
    const val SUBTOTAL_MAX_QTY = 4980.0  // 249 × 20
    const val SEARCH_RESTAURANT_ID_1 = "r1"
    const val SEARCH_RESTAURANT_ID_2 = "r2"
    const val SEARCH_RESTAURANT_ID_3 = "r3"
    const val SEARCH_RESTAURANT_ID_4 = "r4"
    const val SEARCH_RESTAURANT_ID_5 = "r5"
    const val SEARCH_NAME_MEGHANA = "Meghana Foods"
    const val SEARCH_NAME_PIZZA_HUT = "Pizza Hut"
    const val SEARCH_NAME_BURGER_KING = "Burger King"
    const val SEARCH_NAME_BEHROUZ = "Behrouz Biryani"
    const val SEARCH_NAME_GREEN_BOWL = "Green Bowl"
    const val SEARCH_RATING_1 = 4.6
    const val SEARCH_RATING_2 = 4.1
    const val SEARCH_RATING_3 = 3.8
    const val SEARCH_RATING_4 = 4.3
    const val SEARCH_RATING_5 = 4.5
    const val SEARCH_DELIVERY_1 = 30
    const val SEARCH_DELIVERY_2 = 40
    const val SEARCH_DELIVERY_3 = 25
    const val SEARCH_DELIVERY_4 = 55
    const val SEARCH_DELIVERY_5 = 20
    const val SEARCH_COST_1 = 600
    const val SEARCH_COST_2 = 400
    const val SEARCH_COST_3 = 300
    const val SEARCH_COST_4 = 700
    const val SEARCH_COST_5 = 200
    const val CUISINE_BIRYANI = "Biryani"
    const val CUISINE_ANDHRA = "Andhra"
    const val CUISINE_PIZZA = "Pizza"
    const val CUISINE_ITALIAN = "Italian"
    const val CUISINE_BURGER = "Burger"
    const val CUISINE_FAST_FOOD = "Fast Food"
    const val CUISINE_MUGHLAI = "Mughlai"
    const val CUISINE_HEALTHY = "Healthy"
    const val CUISINE_SALADS = "Salads"
    const val QUERY_BIRYANI = "biryani"
    const val QUERY_PIZZA = "pizza"
    const val QUERY_PIZZA_UPPER = "PIZZA"
    const val QUERY_BURGER = "burg"
    const val QUERY_ANDHRA = "andhra"
    const val QUERY_SUSHI = "sushi"
    const val QUERY_WHITESPACE = "   "
    const val RATING_FILTER_40 = 4.0
    const val RATING_FILTER_45 = 4.5
    const val RATING_FILTER_41 = 4.1
    const val RATING_FILTER_39 = 3.9
    const val RATING_FILTER_50 = 5.0
    const val RATING_FILTER_10 = 1.0
    const val DELIVERY_FILTER_30 = 30
    const val DELIVERY_FILTER_20 = 20
    const val DELIVERY_FILTER_39 = 39
    const val DELIVERY_FILTER_35 = 35
    const val DELIVERY_FILTER_0 = 0
    const val RATING_HIGHEST = 4.6
    const val RATING_LOWEST = 3.8
    const val DELIVERY_FASTEST = 20
    const val DELIVERY_SLOWEST = 55
    const val COST_LOWEST = 200
    const val COST_HIGHEST = 700
    const val SEARCH_RESULT_COUNT_ALL = 5
    const val SEARCH_RESULT_COUNT_1 = 1
    const val SEARCH_RESULT_COUNT_2 = 2
    const val SEARCH_RESULT_COUNT_3 = 3
    const val ERR_NETWORK_MSG = "Network error"
    const val HOME_COLLECTION_ID = 1
    const val HOME_COLLECTION_TITLE = "Trending"
    const val HOME_COLLECTION_DESC = "Hot now"
    const val HOME_COLLECTION_COUNT = 10
    const val HOME_COLLECTION_DISCOUNT = "60% OFF"
    const val HOME_CATEGORY_ID_1 = 1
    const val HOME_CATEGORY_ID_2 = 2
    const val HOME_CATEGORY_BIRYANI = "Biryani"
    const val HOME_CATEGORY_PIZZA = "Pizza"
    const val HOME_RESTAURANT_ID_1 = "r1"
    const val HOME_RESTAURANT_ID_2 = "r2"
    const val HOME_RESTAURANT_ID_3 = "r3"
    const val HOME_COLLECTION_COUNT_1 = 1
    const val HOME_CATEGORY_COUNT_2 = 2
    const val HOME_RESTAURANT_COUNT_2 = 2
    const val HOME_RESTAURANT_COUNT_3 = 3
    const val LOC_KORAMANGALA = "Koramangala"
    const val LOC_KORAMANGALA_FULL = "Koramangala, Bengaluru"
    const val LOC_KORAMANGALA_PARTIAL = "Koramangala 5th Block"
    const val LOC_KORAMANGALA_LOWER = "koramangala"
    const val LOC_KORAMANGALA_UPPER = "KORAMANGALA"
    const val LOC_INDIRANAGAR = "Indiranagar"
    const val LOC_HSR = "HSR Layout"
    const val LOC_JAKKUR = "Jakkur"
    const val LOC_MUMBAI = "Mumbai"
    const val LOC_GREATER_KORA = "Greater Koramangala"
    const val LOC_BTM = "BTM Layout"
    const val ADDR_KORAMANGALA = "Koramangala, Bengaluru"
    const val ADDR_INDIRANAGAR = "Indiranagar, Bengaluru"
    const val ADDR_HSR = "HSR Layout, Bengaluru"
    const val ADDR_GREATER_KORA = "Greater Koramangala, Bengaluru"
    const val ADDR_BTM_KORA = "5th Block, Koramangala, Bengaluru"
    const val ADDR_UPPER_KORA = "KORAMANGALA, Bengaluru"
    const val COLLECTION_TITLE_FIRST = "Trending"
    const val ERR_NO_INTERNET_MSG = "No internet"
    const val AVAILABLE_AREAS_COUNT_3 = 3
    const val AVAILABLE_AREAS_COUNT_2 = 2
    const val RESTAURANT_ID_1 = "r1"
    const val RESTAURANT_ID_2 = "r2"
    const val RESTAURANT_ID_3 = "r3"
    const val RESTAURANT_MEGHANA = "Meghana Foods"
    const val RESTAURANT_PIZZA = "Pizza Hut"
    const val RESTAURANT_DOMINOS = "Dominos"
    const val RESTAURANT_EMPIRE = "Empire"
    const val RESTAURANT_BURGER = "Burger King"
    const val RESTAURANT_FRESH = "Fresh Restaurant"
    const val RESTAURANT_OLD_NAME = "Old Name"
    const val RESTAURANT_NEW_NAME = "New Name"
    const val MENU_ITEM_ID = "menu_1"
    const val CATEGORY_BIRYANI = "Biryani"
    const val CATEGORY_STARTERS = "Starters"
    const val CATEGORY_PIZZA = "Pizza"
    const val CATEGORY_BURGER = "Burger"
    const val CATEGORY_THAI = "Thai"
    const val CATEGORY_SUSHI = "Sushi"
    const val MENU_ITEM_CHICK_BIR = "Chicken Biryani"
    const val MENU_ITEM_MUTTON_BIR = "Mutton Biryani"
    const val MENU_ITEM_CHICK_65 = "Chicken 65"
    const val MENU_ITEM_DESC = "Delicious"
    const val MENU_ITEM_PRICE_STR = "249"
    const val MENU_ENTITY_PRICE = 249.0
    const val COLLECTION_ID_1 = 1
    const val COLLECTION_ID_2 = 2
    const val COLLECTION_ID_42 = 42
    const val COLLECTION_TRENDING = "Trending"
    const val COLLECTION_NEW = "New"
    const val COLLECTION_WEEKEND = "Weekend Special"
    const val COLLECTION_HOT = "Hot"
    const val COLLECTION_FRESH = "Fresh"
    const val COLLECTION_GENERIC_DESC = "Desc"
    const val COLLECTION_DISCOUNT_60 = "60% OFF"
    const val COLLECTION_FREE_DEL = "Free Delivery"
    const val COLLECTION_DISCOUNT_30 = "30% off"
    const val COLLECTION_COUNT_20 = 20
    const val COLLECTION_COUNT_10 = 10
    const val COLLECTION_COUNT_15 = 15
    const val CATEGORY_ID_1 = 1
    const val CATEGORY_ID_2 = 2
    const val CATEGORY_ID_3 = 3
    const val CATEGORY_ID_99 = 99
    const val CATEGORY_ID_42 = 42
    const val CUISINE_ID_1 = 1
    const val CUISINE_ID_2 = 2
    const val CUISINE_ID_3 = 3
    const val CUISINE_ID_42 = 42
    const val REVIEW_ID_1 = 1L
    const val REVIEW_ID_2 = 2L
    const val REVIEW_RATING_5 = 5
    const val REVIEW_RATING_4 = 4
    const val REVIEW_TEXT_AMAZING = "Amazing food!"
    const val REVIEW_TEXT_GOOD_BIR = "Good biryani"
    const val REVIEW_TEXT_GOOD = "Good"
    const val REVIEW_TIME_2_DAYS = "2 days ago"
    const val REVIEW_TIME_1_WEEK = "1 week ago"
    const val REVIEW_TIME_1_DAY = "1 day"
    const val REVIEW_USER_SWAPNA = "Swapna"
    const val REVIEW_USER_PRIYA = "Priya"
    const val REVIEW_USER_GENERIC = "User"
    const val REVIEW_IMG_URL = "https://img.jpg"
    const val REVIEW_TOTAL_COUNT = 2
    const val REVIEW_TOTAL_1 = 1
    const val USER_ID_1 = "u1"
    const val USER_ID_FIREBASE = "fb_uid"
    const val USER_ID_UID = "uid_123"
    const val USER_ID_API = "api_user_1"
    const val USER_ID_GUEST = "guest"
    const val USER_NAME_SWAPNA = "Swapna"
    const val USER_NAME_FIREBASE = "Firebase User"
    const val USER_EMAIL_SWAPNA = "swapna@example.com"
    const val USER_EMAIL_FIREBASE = "fb@example.com"
    const val USER_PHONE_VALID = "+919876543210"
    const val ADDRESS_ID_1 = "a1"
    const val ADDRESS_ID_2 = "a2"
    const val ADDRESS_LABEL_HOME = "Home"
    const val ADDRESS_LABEL_WORK = "Work"
    const val ADDRESS_FULL_1 = "123 Main Street"
    const val ADDRESS_FULL_2 = "123 St"
    const val ADDRESS_FULL_3 = "456 Office"
    const val ADDRESS_LOC_KORAMANGALA = "Koramangala"
    const val ADDRESS_LOC_HSR = "HSR Layout"
    const val ORDER_ID_1 = "o1"
    const val ORDER_COUNT_1 = 1
    const val ERR_WRONG_OTP_MSG = "Wrong OTP"
    const val ERR_NETWORK = "Network error"
    const val ERR_SERVER = "Server error"
    const val ERR_DB = "DB error"
    const val ERR_TIMEOUT = "Timeout"
    const val ERR_FIREBASE = "Firebase error"
    const val ERR_RATE_LIMIT = "Rate limit exceeded"
    const val ERR_NO_INTERNET = "No internet"
    const val ERR_BACKGROUND_MSG =
        "App is in background. Please reopen and try again."
    const val ENTITY_RATING = 4.2
    const val ENTITY_RATING_TEXT = "Very Good"
    const val ENTITY_RATING_COLOR = "5BA829"
    const val ENTITY_VOTES = 100
    const val ENTITY_DELIVERY_TIME = 30
    const val ENTITY_DELIVERY_FEE = 30.0
    const val ENTITY_COST_TWO = 600
    const val ENTITY_CUISINES_JSON = """["Biryani"]"""
    const val ENTITY_ADDRESS = "Bengaluru"
    const val ENTITY_LOCALITY = "Koramangala"
    const val ENTITY_LAT = "12.93"
    const val ENTITY_LNG = "77.62"
    const val ENTITY_ZIPCODE = "560095"
    const val ENTITY_CITY_ID = 4
    const val ENTITY_PRICE_RANGE = 2
    const val ENTITY_CURRENCY = "Rs."
    const val MENU_ID_4 = "m4"
    const val MENU_ID_SIMPLE = "m2"
    const val MENU_ID_UNKNOWN = "m999"
    const val CART_UUID_1 = "cart_uuid_1"
    const val CART_UUID_2 = "cart_uuid_2"
    const val CART_ID_STR_1 = "cart_id_1"
    const val PRICE_179 = 179.0
    const val PRICE_199 = 199.0
    const val PRICE_349 = 349.0
    const val PRICE_600 = 600.0
    const val EXTRA_PRICE_100 = 100.0
    const val TOTAL_PRICE_299 = 299.0    // (249+50) × 1
    const val TOTAL_PRICE_349_P = 349.0    // (249+100) × 1
    const val TOTAL_PRICE_498 = 498.0    // 249 × 2
    const val TOTAL_PRICE_1047 = 1047.0   // (249+100) × 3
    const val TOTAL_PRICE_100 = 100.0    // 50 × 2
    const val MENU_ITEM_PLAIN_NAAN = "Plain Naan"
    const val MENU_ITEM_PANEER_TIKKA = "Paneer Tikka"
    const val SUBTOTAL_249_349 = 598.0    // 249 + 349
    const val SUBTOTAL_249_X2 = 498.0    // 249 × 2
    const val MSG_REMOVED = " removed"
    const val MSG_REMOVED_FROM_CART = " removed from cart"
    const val ERR_CART_EMPTY_MSG = "Cart is empty"
    const val ERR_MIN_ORDER_PREFIX = "Minimum order is ₹"
    const val CART_RESTAURANT_ID = "r1"     // default restaurantId from fakeMenuItem
    const val CUSTOMISE_GROUP_SIZE = "size_group"
    const val CUSTOMISE_GROUP_SPICE = "spice_group"
    const val CUSTOMISE_OPT_REGULAR = "regular"
    const val CUSTOMISE_OPT_LARGE = "large"
    const val CUSTOMISE_OPT_EXTRA_LARGE = "extra_large"
    const val CUSTOMISE_OPT_MILD = "mild"
    const val CUSTOMISE_OPT_MEDIUM = "medium"
    const val CUSTOMISE_OPT_HOT = "hot"
    const val CUSTOMISE_NAME_SIZE = "Size"
    const val CUSTOMISE_NAME_SPICE = "Spice Level"
    const val CUSTOMISE_LABEL_REGULAR = "Regular"
    const val OPT_ID_1 = "opt1"
    const val OPT_ID_2 = "opt2"
    const val OPT_ID_3 = "opt3"
    const val OPT_ID_4 = "opt4"
    const val OPT_ID_5 = "opt5"
    const val ORDER_TIME_YESTERDAY = "Yesterday, 1:45 PM"
    const val ORDER_ITEM_QTY_2 = 2
    const val EMPTY_JSON_ARRAY ="[]"
    const val SINGLE_ITEM_MENU_ID = "menu_1"
    const val MENU_PRICE_STR = "249"
    const val API_IS_NOT_VEG = 0
    const val API_IS_RECOMMENDED = 1
    const val FAKE_ITEM_NAME_PREFIX = "Test Item "
    const val FAKE_MENU_ID_PREFIX = "menu_"
    const val FAKE_CART_ID_PREFIX = "test_item_"
    const val ERROR_MESSAGE = "Something went wrong"
    const val CATEGORY_BREADS = "Breads"
    const val CUSTOMISE_LABEL_LARGE = "Large"
    const val CUSTOMISE_LABEL_XL = "Extra Large"
    const val CUSTOMISE_LABEL_MILD = "Mild"
    const val CUSTOMISE_LABEL_MEDIUM = "Medium"
    const val CUSTOMISE_LABEL_HOT = "Hot"
    const val CUSTOMISE_COUNT_SIZE = 2    // number of customisation groups
    const val QTY_15_REPEAT = 15   // repeat to test MAX cap
    const val ERR_ITEM_NOT_FOUND_MSG = "Item not found"
    const val ERR_FAILED_LOAD_ITEM_MSG = "Failed to load item"
    const val MSG_BIRYANI_ADDED_CART = "Chicken Biryani added to cart 🛒"
    const val ERR_CART_FULL = "Cart is full"
    const val MENU_ITEM_DESC_PREFIX = "Delicious "
    const val MENU_DESC_BIRYANI = "Delicious Chicken Biryani"
    const val MENU_DESC_NAAN = "Delicious Plain Naan"
    const val RESTAURANT_ADDRESS_KORA = "Koramangala, Bengaluru"
    const val OFFER_50_OFF = "50% off"
    const val RESTAURANT_RATING_45 = 4.5
    const val RESTAURANT_VOTES_5000 = 5000
    const val RESTAURANT_COST_500 = 500
    const val RESTAURANT_MIN_ORDER_100 = 100
    const val CATEGORY_STARTERS_CAP = "Starters"
    const val ERR_COULD_NOT_LOAD_REST = "Could not load restaurant"
    const val ERR_COULD_NOT_ADD_CART = "Could not add to cart"
    const val MENU_COUNT_BIRYANI = 2    // items in Biryani category
    const val MENU_COUNT_STARTERS = 2    // items in Starters category
    const val MENU_CATEGORY_COUNT = 2    // total categories
    const val CART_COUNT_3 = 3    // 3 cart items
    const val CART_QTY_SUM_3 = 3    // qty 2 + qty 1


    const val CUISINE_CHINESE = "Chinese"
    const val QUERY_BURGER_FULL = "burger"
    const val QUERY_P = "p"
    const val QUERY_B = "b"

    const val DELIVERY_FILTER_45 = 45

    const val SEARCH_RESULT_COUNT_4 = 4

    const val CUISINE_ID_4 = 4

    const val SEARCH_VM_R1 = "r1"
    const val SEARCH_VM_R2 = "r2"
    const val SEARCH_VM_R3 = "r3"
    const val SEARCH_VM_MEGHANA = "Meghana Foods"
    const val SEARCH_VM_PIZZA_HUT = "Pizza Hut"
    const val SEARCH_VM_BURGER_KING = "Burger King"
    const val SEARCH_VM_RATING_1 = 4.6
    const val SEARCH_VM_RATING_2 = 4.1
    const val SEARCH_VM_RATING_3 = 3.9


    const val HOME_COLL_TRENDING = "Trending"
    const val HOME_COLL_NEWLY_OPENED = "Newly Opened"
    const val HOME_COLL_POPULAR = "Popular"
    const val HOME_COLL_JUST_LAUNCHED = "Just launched"
    const val HOME_COLL_60_OFF = "60% OFF"
    const val HOME_COLL_FREE_DEL = "Free Delivery"
    const val HOME_COLL_COUNT_20 = 20
    const val HOME_COLL_COUNT_10 = 10
    const val HOME_COLL_ID_1 = 1
    const val HOME_COLL_ID_2 = 2
    const val HOME_REST_R1 = "r1"
    const val HOME_REST_R2 = "r2"
    const val HOME_REST_R3 = "r3"
    const val HOME_REST_R4 = "r4"
    const val HOME_REST_MEGHANA = "Meghana Foods"
    const val HOME_REST_PIZZA_HUT = "Pizza Hut"
    const val HOME_REST_BURGER_KING = "Burger King"
    const val HOME_REST_EMPIRE = "Empire"
    const val HOME_REST_COUNT_4 = 4
    const val HOME_REST_COUNT_2 = 2
    const val HOME_REST_COUNT_1 = 1
    const val HOME_CAT_COUNT_2 = 2
    const val HOME_COLL_SIZE_2 = 2
    const val HOME_CART_COUNT_3 = 3
    const val HOME_AVAILABLE_AREAS_3 = 3
    const val HOME_LOC_WHITEFIELD = "Whitefield"
    const val HOME_LOC_HSR = "HSR Layout"
    const val HOME_LOC_INDIRANAGAR = "Indiranagar"
    const val HOME_LOC_KORAMANGALA = "Koramangala"
    const val ERR_NO_INTERNET_HOME = "No internet"
    const val ERR_ERROR_STR = "error"
    const val GPS_KORAMANGALA = "Koramangala 5th Block, Bengaluru"
    const val GPS_INDIRANAGAR = "100 Feet Road, Indiranagar, Bengaluru"
    const val GPS_WHITEFIELD = "ITPL Main Road, Whitefield, Bengaluru"
    const val GPS_BANGALORE = "MG Road, Bangalore"
    const val GPS_DELHI = "Connaught Place, New Delhi"
    const val GPS_MUMBAI = "Bandra, Mumbai"
    const val GPS_CHENNAI = "Anna Nagar, Chennai"
    const val GPS_MYSORE = "Devaraja Market, Mysore"
    const val GPS_LAT = 12.9352
    const val GPS_LNG = 77.6245
    const val GPS_BTM = "BTM Layout, Bengaluru"
    const val GPS_JP_NAGAR = "JP Nagar 3rd Phase, Bengaluru"
    const val GPS_MARATHAHALLI = "Marathahalli, Outer Ring Road, Bengaluru"
    const val GPS_BELLANDUR = "Bellandur, Bengaluru"
    const val GPS_SARJAPUR = "Sarjapur Road, Bengaluru"
    const val GPS_YELAHANKA = "Yelahanka, Bengaluru"
    const val GPS_HEBBAL = "Hebbal, Bengaluru"
    const val GPS_JAYANAGAR = "Jayanagar, Bengaluru"
    const val GPS_MALLESHWARAM = "Malleshwaram, Bengaluru"
    const val GPS_KR_PURAM = "KR Puram, Bengaluru"
    const val GPS_MANGALORE = "Hampankatta, Mangalore"
    const val ERR_PERMISSION_DENIED_GPS = "permission denied"
    const val ERR_GPS_DISABLED_MSG = "GPS disabled"
    const val ERR_UNKNOWN_CRASH = "unknown crash"
    const val LOC_KEYWORD_PERMISSION = "permission"
    const val LOC_KEYWORD_GPS = "GPS"
    const val LOC_KEYWORD_MANUALLY = "manually"
    const val LOC_KEYWORD_DENIED = "denied"
    const val LOC_WHITEFIELD_FULL = "Whitefield"
    const val LOC_INDIRANAGAR_FULL = "Indiranagar"
    const val LOC_SAVE_HSR = "HSR Layout"
    const val USER_NAME_UPDATED = "Swapna Reddy"
    const val USER_EMAIL_UPDATED = "updated@example.com"
    const val USER_EMAIL_NEW = "new@example.com"
    const val PROFILE_FALLBACK_NAME = "Add your name"
    const val PROFILE_FALLBACK_EMAIL = "Add email address"
    const val ERR_COULD_NOT_LOAD_PROFILE = "Could not load profile"
    const val MSG_PROFILE_UPDATED_TICK = "Profile updated ✅"
    const val ERR_NAME_EMPTY_MSG = "Name cannot be empty"
    const val ERR_NO_USER_FOUND_MSG = "No user found. Please login again."
    const val MSG_ADDRESS_REMOVED = "Address removed"
    const val ERR_DELETE_FAILED = "Delete failed"
    const val ERR_LOGOUT_FAILED_MSG = "Logout failed. Please try again."
    const val ORDER_STATUS_DELIVERED_CAP = "Delivered"
    const val ORDER_TIME_FRIENDLY = "Today, 12:00 PM"
    const val ORDER_ID_2 = "o2"
    const val ORDER_COUNT_2 = 2
    const val PROFILE_SELECTED_LOC = "Koramangala"
    const val HOME_ADDR_COUNT_2          = 2
    const val HOME_SEARCH_QUERY_BURGER   = "Burger"
    const val HOME_RATING_TEXT_EXCELLENT = "Excellent"
    const val HOME_RATING_COLOR          = "#3F7E00"
    const val HOME_SOUTH_INDIAN          = "South Indian"
    const val HOME_TEST_REST_NAME        = "Test Restaurant"
    const val HOME_DELIVERY_FEE          = 30.0
    const val HOME_OFFERS_50_OFF         = "50% off"
    const val CATEGORY_BIRYANI_CAT = "Biryani"
    const val ADDRESS_MG_ROAD = "123 MG Road, Koramangala"
    const val ADDRESS_RMZ = "RMZ Ecospace, Bellandur"
    const val ADDRESS_NEAR_FORUM = "Near Forum Mall"
    const val ADDRESS_NEAR_ORR = "Near Outer Ring Road"
    const val QTY_10                  = 10
    const val PRICE_1000              = 1000.0    // 100 × 10
    const val PRICE_398               = 398.0     // 199 × 2
    const val PRICE_329               = 329.0     // (249+50+30) × 1
    const val PRICE_405               = 405.0     // (100+35) × 3
    const val PRICE_500               = 500.0     // 100 × 5
    const val PRICE_300               = 300.0
    const val EXTRA_PRICE_30          = 30.0
    const val EXTRA_PRICE_20          = 20.0
    const val EXTRA_PRICE_10          = 10.0
    const val EXTRA_PRICE_5           = 5.0
    const val BREAKDOWN_TAXES_249     = 12.45     // 249 × 0.05
    const val BREAKDOWN_TOTAL_249     = 291.45    // 249 + 30 + 12.45
    const val BREAKDOWN_TAXES_698     = 34.9      // 698 × 0.05
    const val ADDRESS_MAIN_ST         = "123 Main St"
    const val ADDRESS_LANDMARK_PARK   = "Near Park"
    const val ADDRESS_LAT_12_93       = 12.93
    const val ADDRESS_LNG_77_62       = 77.62
    const val ADDRESS_OFFICE_RD       = "456 Office Rd"
    const val ADDRESS_FULL_123_ST     = "123 St"   // abbreviated in null-landmark test
    const val EMAIL_SHORT             = "s@example.com"
    const val PHONE_SHORT             = "+91"
    const val ORDER_STATUS_PENDING    = "Pending"
    const val ORDER_TIME_TOMORROW     = "Tomorrow"
    const val ORDER_TIME_TODAY_SHORT  = "Today"
    const val RESTAURANT_ID_R99       = "r99"
    const val PRICE_STR_249_RS        = "249 Rs."
    const val PRICE_STR_349_RUPEE     = "₹349"
    const val PRICE_STR_99_50         = "99.50"
    const val PRICE_STR_199           = "199"
    const val PRICE_STR_349           = "349"
    const val PRICE_STR_RS_449        = "Rs. 449"
    const val PRICE_PARSED_99_5       = 99.5
    const val PRICE_PARSED_RS_449     = 0.449
    const val PRICE_STR_INVALID       = "N/A"
    const val MENU_DESCRIPTION_BIRYANI = "Delicious Biryani"
    const val CATEGORY_EMPTY_NAME     = "Empty Category"
    const val CATEGORY_EMPTY_SHORT    = "Empty"
    const val API_IS_VEG              = 1
    const val MENU_DTO_ID_1           = "1"
    const val MENU_DTO_ID_2           = "2"
    const val THUMB_URL_HTTPS         = "https://thumb.jpg"
    const val CUISINES_JSON_BIRYANI_SI = """["Biryani","South Indian"]"""
    const val OFFERS_JSON_50_OFF      = """["50% off"]"""
    const val HIGHLIGHTS_JSON_TWO     = """["Dine-in","Takeaway"]"""
    const val HIGHLIGHTS_JSON_ONE     = """["Dine-in"]"""
    const val DISTANCE_KM_1_5         = 1.5
    const val PHONE_11_DIGITS         = "+911234567890"
    const val ENTITY_NAME_TEST        = "Test"
    const val HIGHLIGHT_DINE_IN       = "Dine-in"
    const val HIGHLIGHT_TAKEAWAY      = "Takeaway"
    const val MENU_DESCRIPTION_SHORT  = "Delicious"

}