package com.swapna.foodapp.utils

object AndroidTestConstants {

    const val CMD_WAKEUP = "input keyevent KEYCODE_WAKEUP"
    const val CMD_DISMISS_KEYGUARD = "wm dismiss-keyguard"
    const val HOME_DELIVERING_TO = "Delivering to"
    const val HOME_SEARCH_HINT = "Search for restaurants and food"
    const val HOME_GO_TO_CART_DESC = "Go to cart"
    const val HOME_LOCATION_ICON_DESC = "Location"
    const val CART_BADGE_ZERO = "0"
    const val CART_COUNT_ONE = 1
    const val CART_COUNT_THREE = 3
    const val HOME_SECTION_RESTAURANTS = "Restaurants Near You"
    const val HOME_REST_R1 = "r1"
    const val HOME_REST_R2 = "r2"
    const val HOME_REST_MEGHANA = "Meghana Foods"
    const val HOME_REST_PIZZA_HUT = "Pizza Hut"
    const val HOME_REST_ADDRESS = "Koramangala, Bengaluru"
    const val HOME_ERROR_NOT_IN_SUBSTR = "not in"
    const val HOME_CHANGE_DELIVERY_LOCATION = "Change Delivery Location"
    const val HOME_NO_RESTAURANTS_FOUND = "No restaurants found"
    const val HOME_SECTION_CATEGORIES = "What's on your mind?"
    const val HOME_CATEGORY_ID_1 = 1
    const val HOME_CATEGORY_BIRYANI = "Biryani"
    const val HOME_SECTION_OFFERS = "Exciting Offers 🔥"
    const val HOME_COLL_ID_1 = 1
    const val HOME_COLL_TRENDING = "Trending"
    const val HOME_COLL_TRENDING_NOW = "Trending Now"
    const val HOME_COLL_RESTAURANT_COUNT = 10
    const val HOME_COLL_DISCOUNT = "20% off"            // AppConstants.TRY_AGAIN
    const val ERR_NO_INTERNET_CONNECTION = "No internet connection"
    const val ERR_NETWORK_ERROR = "Network error"
    const val HOME_OFFLINE_SUBSTR = "offline"
    const val HOME_DELIVERY_LOCATION_TITLE = "Delivery Location"
    const val HOME_DELIVERY_LOCATION_SUBTITLE = "Where should we deliver?"
    const val HOME_CLOSE_ICON_DESC = "Close"
    const val HOME_USE_CURRENT_LOCATION = "Use Current location"
    const val HOME_NO_SAVED_ADDRESSES = "No saved addresses"
    const val HOME_POPULAR_LOCATION = "Koramangala, Bengaluru"
    const val HOME_ADDRESS_ID = "a1"
    const val HOME_ADDRESS_LABEL_HOME = "Home"
    const val HOME_ADDRESS_FULL = "42, 3rd Floor, Koramangala"
    const val HOME_ADDRESS_LANDMARK = ""
    const val HOME_ADDRESS_LAT = 12.93
    const val HOME_ADDRESS_LNG = 77.62
    const val HOME_USER_ID = "u1"
    const val HOME_USER_NAME = "Swapna"
    const val HOME_USER_EMAIL = "swapna@example.com"
    const val HOME_USER_PHONE = "+919876543210"
    const val HOME_USER_SELECTED_LOCATION = "Koramangala"
    const val LOGIN_BURGER_EMOJI = "🍔"
    const val LOGIN_TITLE = "Login"
    const val LOGIN_SUBTITLE = "Enter your mobile number to continue"
    const val LOGIN_BTN_SEND_OTP = "Send OTP"
    const val LOGIN_BTN_VERIFY_OTP = "Verify OTP"
    const val LOGIN_PHONE_ERROR_MSG = "Enter a valid 10-digit phone number"
    const val LOGIN_SHORT_PHONE = "12345"
    const val LOGIN_VALID_PHONE_10 = "1234567890"   // caps test phone
    const val LOGIN_VALID_PHONE = "9876543210"   // auth flow phone
    const val LOGIN_VALID_OTP = "123456"
    const val LOGIN_WRONG_OTP = "000000"
    const val LOGIN_SHORT_OTP = "1234"
    const val LOGIN_OTP_EXTRA_DIGITS = "78"
    const val LOGIN_OTP_SINGLE_CHAR = "1"
    const val LOGIN_NETWORK_UNAVAILABLE = "Network unavailable"
    const val LOGIN_GENERIC_ERROR = "Error"
    const val LOGIN_WRONG_OTP_MSG = "Wrong OTP"
    const val LOGIN_WRONG_OTP_FULL_MSG =
        "Wrong OTP. Please check and try again."
    const val LOGIN_USER_ID = "u1"
    const val LOGIN_USER_NAME = "Swapna"
    const val LOGIN_USER_EMAIL = ""             // empty email in login flow
    const val LOGIN_USER_PHONE = "9876543210"
    const val ASSERT_STILL_LOADING = "Still loading"
    const val ASSERT_EXPECTED_NO_FILTER = "Expected NO_FILTER but got"
    const val ASSERT_LOGIN_NOT_CALLED =
        "onLoginSuccess was not called after correct OTP"
    const val ASSERT_EXPECTED_DELIVERY_TAB = "Expected DELIVERY tab by default"
    const val ASSERT_EXPECTED_DINING_TAB = "Expected DINING tab"
    const val ASSERT_EXPECTED_DELIVERY_BACK =
        "Expected DELIVERY after switching back"
    const val FAKE_REST_ID_R1 = "r1"
    const val FAKE_REST_MEGHANA = "Meghana Foods"
    const val FAKE_REST_RATING_4_6 = 4.6
    const val FAKE_REST_RATING_TEXT_EX = "Excellent"
    const val FAKE_REST_RATING_COLOR = "#3F7E00"
    const val FAKE_REST_TOTAL_VOTES_12500 = 12500
    const val FAKE_REST_DELIVERY_TIME_30 = 30
    const val FAKE_REST_DELIVERY_FEE_FREE = 0.0
    const val FAKE_REST_MIN_ORDER_100 = 100
    const val FAKE_REST_ADDRESS_KORA = "Koramangala, Bengaluru"
    const val FAKE_REST_LOCALITY_KORA = "Koramangala"
    const val FAKE_REST_DISTANCE_KM_2_5 = 2.5
    const val FAKE_REST_COST_FOR_TWO_400 = 400
    const val FAKE_REST_OPENING_HOURS = "11 AM - 11 PM"
    const val FAKE_REST_OFFER_20_OFF = "20% off above ₹499"
    const val FAKE_REST_CUISINE_BIRYANI = "Biryani"
    const val FAKE_REST_CUISINE_SOUTH_IND = "South Indian"
    const val FAKE_REST_RESTAURANT_ID = "r1"
    const val FAKE_MENU_ID_M1 = "m1"
    const val FAKE_MENU_ID_M2 = "m2"
    const val FAKE_MENU_ID_M3 = "m3"
    const val FAKE_MENU_ID_M4 = "m4"
    const val FAKE_MENU_CHICK_BIR = "Chicken Biryani"
    const val FAKE_MENU_MUTTON_BIR = "Mutton Biryani"
    const val FAKE_MENU_CHICK_65 = "Chicken 65"
    const val FAKE_MENU_PANEER_TIKKA = "Paneer Tikka"
    const val FAKE_MENU_PRICE_249 = 249.0
    const val FAKE_MENU_PRICE_349 = 349.0
    const val FAKE_MENU_PRICE_199 = 199.0
    const val FAKE_MENU_PRICE_179 = 179.0
    const val FAKE_MENU_PRICE_100 = 100.0
    const val FAKE_MENU_CATEGORY_BIRYANI = "Biryani"
    const val FAKE_MENU_CATEGORY_STARTERS = "Starters"
    const val FAKE_MENU_CATEGORY_TEST = "Test"
    const val FAKE_MENU_DESC_PREFIX = "Delicious "
    const val FAKE_ERROR_SOMETHING_WRONG = "Something went wrong"
    const val FAKE_CART_ID_PREFIX = "fake_"
    const val FAKE_CART_MENU_ID_PREFIX = "m"
    const val FAKE_CART_ITEM_NAME_PREFIX = "Item "
    const val FAKE_CART_RESTAURANT_ID = "r1"
    const val FAKE_USER_ID_U1 = "u1"
    const val FAKE_USER_NAME_TEST = "Test"
    const val FAKE_USER_EMAIL_EMPTY = ""
    const val FAKE_USER_PHONE = "9876543210"
    const val FAKE_ERR_NOT_IMPLEMENTED = "Not implemented"
    const val CART_BADGE_ONE = "1"
    const val CART_BADGE_THREE = "3"
    const val CART_EMPTY_MESSAGE = "Your cart is empty"
    const val CART_BROWSE_FOOD = "Browse Food"
    const val CART_INCREASE_QTY_CD = "Increase quantity"
    const val CART_DECREASE_QTY_CD = "Decrease quantity"
    const val CART_VEG_INDICATOR_CD = "Veg"
    const val CART_MIN_ORDER_SUBSTR = "Minimum order"
    const val CART_ITEM_REMOVED_SUFFIX = " removed"
    const val CART_ITEMS_0 = "0 items"
    const val CART_ITEMS_2 = "2 items"
    const val CART_ITEMS_5 = "5 items"
    const val CART_QTY_STR_1 = "1"
    const val CART_QTY_STR_2 = "2"
    const val CART_PRICE_249 = "₹249"
    const val CART_PRICE_498 = "₹498"
    const val CART_AMOUNT_249 = "249"
    const val FAKE_CART_ITEM_ID_PREFIX = "cart_"
    const val FAKE_CART_ID_C1 = "c1"
    const val FAKE_CART_ID_C2 = "c2"
    const val FAKE_MENU_MARGHERITA_PIZZA = "Margherita Pizza"
    const val FAKE_MENU_PLAIN_NAAN = "Plain Naan"
    const val FAKE_MENU_PLAIN_WATER = "Plain Water"
    const val FAKE_MENU_PRICE_50 = 50.0
    const val FAKE_MENU_PRICE_10 = 10.0
    const val ASSERT_UPDATE_QTY_INCREMENT = "Expected updateQuantity to be called after increment"
    const val ASSERT_UPDATE_QTY_DECREMENT =
        "Expected updateQuantity called when decrementing from qty 2"
    const val ASSERT_REMOVE_ITEM_FROM_QTY_1 =
        "Expected removeItem called when decrementing from qty 1"
    const val ASSERT_CLEAR_CART_CALLED = "Expected clearCart called after valid order placed"
    const val ASSERT_CLEAR_CART_NOT_CALLED = "Cart must NOT be cleared when minimum order not met"
    const val FAKE_REST_RATING_STR = "4.6"    // Double → UI display substring
    const val FAKE_REST_DELIVERY_TIME_STR = "30"     // Int → UI display substring
    const val ASSERT_REST_ADD_ITEM_CALLED = "Expected addToCart called after ADD tap"
    const val ASSERT_REST_UPDATE_QTY_CALLED = "Expected updateQuantity called after increment"
    const val ASSERT_REST_REMOVE_ITEM_CALLED =
        "Expected removeItem called when decrementing from qty 1"
    const val PROFILE_DISPLAY_NAME = "Swapna"
    const val PROFILE_DISPLAY_EMAIL = "swapna@example.com"
    const val PROFILE_PHONE = "+919876543210"
    const val PROFILE_ADDRESS_ID = "addr1"
    const val PROFILE_ADDRESS_LABEL = "Home"
    const val PROFILE_ADDRESS_FULL = "42, 3rd Floor, Koramangala"
    const val PROFILE_ORDER_ID = "ord1"
    const val PROFILE_ORDER_REST_NAME = "Meghana Foods"
    const val PROFILE_ORDER_STATUS = "Delivered"
    const val PROFILE_ORDER_TIME = "2 days ago"
    const val PROFILE_ORDER_TOTAL = 450.0
    const val PROFILE_ORDER_ITEM_NAME = "Chicken Biryani"
    const val PROFILE_EDIT_NAME = "Swapna P"
    const val PROFILE_EDIT_EMAIL = "swapna.p@example.com"
    const val ASSERT_PROFILE_LOGOUT_CALLED = "Expected logout to trigger NavigateToLogin"
    const val ASSERT_PROFILE_SAVE_CALLED = "Expected profile save to be called"
    const val ASSERT_PROFILE_DELETE_CALLED = "Expected address delete to be called"
    const val PROFILE_USER_ID = "u1"
    const val PROFILE_ORDER_STATUS_DELIVERED = "Delivered"
    const val TEST_ROUTE_CART = "cart"
    const val TEST_ROUTE_RESTAURANT = "restaurant"
    const val TEST_ROUTE_PROFILE = "profile"
    const val TEST_ARG_RESTAURANT_ID = "restaurantId"
    const val TEST_ARG_MENU_ITEM_ID = "menuItemId"
    const val TEST_ROUTE_PRODUCT =
        "product/{$TEST_ARG_RESTAURANT_ID}/{$TEST_ARG_MENU_ITEM_ID}"
    const val ASSERT_LOGOUT_CALLED = "Expected logout() to be called on UserRepository"
    const val ASSERT_DELETED_ADDRESS_ID_FMT = "Expected deleted id = %s but got %s"

}