package com.swapna.foodapp.utils

object AndroidTestConstants {

    const val HOME_DELIVERING_TO            = "Delivering To"
    const val HOME_SEARCH_HINT              = "Search restaurants or food..."
    const val HOME_GO_TO_CART_DESC          = "Go to cart"
    const val HOME_LOCATION_ICON_DESC       = "Location"
    const val CART_BADGE_ZERO               = "0"
    const val CART_COUNT_ONE                = 1
    const val CART_COUNT_THREE              = 3
    const val HOME_SECTION_RESTAURANTS      = "Restaurants Near You"
    const val HOME_REST_R1                  = "r1"
    const val HOME_REST_R2                  = "r2"
    const val HOME_REST_MEGHANA             = "Meghana Foods"
    const val HOME_REST_PIZZA_HUT           = "Pizza Hut"
    const val HOME_REST_RATING              = 4.5
    const val HOME_REST_RATING_TEXT         = "Excellent"
    const val HOME_REST_RATING_COLOR        = "#3F7E00"
    const val HOME_REST_TOTAL_VOTES         = 1000
    const val HOME_REST_DELIVERY_TIME       = 30
    const val HOME_REST_DELIVERY_FEE        = 0.0    // free delivery in UI test fake
    const val HOME_REST_MIN_ORDER           = 100
    const val HOME_REST_ADDRESS             = "Koramangala, Bengaluru"
    const val HOME_REST_LOCALITY            = "Koramangala"
    const val HOME_REST_COST_FOR_TWO        = 400
    const val HOME_REST_DISTANCE_KM         = 1.0
    const val HOME_REST_CUISINE_BIRYANI     = "Biryani"
    const val HOME_REST_CUISINE_SOUTH_IND   = "South Indian"
    const val HOME_ERROR_NOT_IN_SUBSTR      = "not in"
    const val HOME_CHANGE_DELIVERY_LOCATION = "Change Delivery Location"
    const val HOME_NO_RESTAURANTS_FOUND     = "No restaurants found"
    const val HOME_SECTION_CATEGORIES       = "What's on your mind?"
    const val HOME_CATEGORY_ID_1            = 1
    const val HOME_CATEGORY_BIRYANI         = "Biryani"
    const val HOME_SECTION_OFFERS           = "Exciting Offers 🔥"
    const val HOME_COLL_ID_1               = 1
    const val HOME_COLL_TRENDING            = "Trending"
    const val HOME_COLL_TRENDING_NOW        = "Trending Now"
    const val HOME_COLL_RESTAURANT_COUNT    = 10
    const val HOME_COLL_DISCOUNT            = "20% off"
    const val HOME_ERROR_TITLE_WRONG        = "Something went wrong"  // AppConstants.WRONG
    const val HOME_RETRY_BUTTON_TEXT        = "Try Again"             // AppConstants.TRY_AGAIN
    const val ERR_NO_INTERNET_CONNECTION    = "No internet connection"
    const val ERR_NETWORK_ERROR             = "Network error"
    const val HOME_OFFLINE_SUBSTR           = "offline"
    const val HOME_DELIVERY_LOCATION_TITLE  = "Delivery Location"
    const val HOME_DELIVERY_LOCATION_SUBTITLE = "Where should we deliver?"
    const val HOME_CLOSE_ICON_DESC          = "Close"
    const val HOME_USE_CURRENT_LOCATION     = "Use Current Location"
    const val HOME_NO_SAVED_ADDRESSES       = "No saved addresses"
    const val HOME_POPULAR_LOCATION         = "Koramangala, Bengaluru"
    const val HOME_ADDRESS_ID               = "a1"
    const val HOME_ADDRESS_LABEL_HOME       = "Home"
    const val HOME_ADDRESS_FULL             = "42, 3rd Floor, Koramangala"
    const val HOME_ADDRESS_LANDMARK         = ""
    const val HOME_ADDRESS_LAT              = 12.93
    const val HOME_ADDRESS_LNG              = 77.62
    const val HOME_USER_ID                  = "u1"
    const val HOME_USER_NAME                = "Swapna"
    const val HOME_USER_EMAIL               = "swapna@example.com"
    const val HOME_USER_PHONE               = "+919876543210"
    const val HOME_USER_SELECTED_LOCATION   = "Koramangala"
    const val HOME_TAB_DELIVERY             = "Delivery"
    const val HOME_TAB_DINING               = "Dining"
    const val HOME_TAB_PROFILE              = "Profile"
    const val LOGIN_BURGER_EMOJI            = "🍔"
    const val LOGIN_TITLE                   = "Login"
    const val LOGIN_SUBTITLE                = "Enter your mobile number to continue"
    const val LOGIN_BTN_SEND_OTP            = "Send OTP"
    const val LOGIN_BTN_VERIFY_OTP          = "Verify OTP"
    const val LOGIN_PHONE_ERROR_MSG         = "Enter a valid 10-digit phone number"
    const val LOGIN_SHORT_PHONE             = "12345"
    const val LOGIN_VALID_PHONE_10          = "1234567890"   // caps test phone
    const val LOGIN_VALID_PHONE             = "9876543210"   // auth flow phone
    const val LOGIN_PHONE_EXTRA_DIGIT       = "1"
    const val LOGIN_VALID_OTP               = "123456"
    const val LOGIN_WRONG_OTP               = "000000"
    const val LOGIN_SHORT_OTP               = "1234"
    const val LOGIN_OTP_EXTRA_DIGITS        = "78"
    const val LOGIN_OTP_SINGLE_CHAR         = "1"
    const val LOGIN_NETWORK_UNAVAILABLE     = "Network unavailable"
    const val LOGIN_GENERIC_ERROR           = "Error"
    const val LOGIN_WRONG_OTP_MSG           = "Wrong OTP"
    const val LOGIN_WRONG_OTP_FULL_MSG      =
        "Wrong OTP. Please check and try again."
    const val LOGIN_USER_ID                 = "u1"
    const val LOGIN_USER_NAME               = "Swapna"
    const val LOGIN_USER_EMAIL              = ""             // empty email in login flow
    const val LOGIN_USER_PHONE              = "9876543210"
    const val ASSERT_STILL_LOADING          = "Still loading"
    const val ASSERT_EXPECTED_NO_FILTER     = "Expected NO_FILTER"
    const val ASSERT_LOGIN_NOT_CALLED       =
        "onLoginSuccess was not called after correct OTP"
    const val ASSERT_EXPECTED_DELIVERY_TAB  = "Expected DELIVERY tab by default"
    const val ASSERT_EXPECTED_DINING_TAB    = "Expected DINING tab"
    const val ASSERT_EXPECTED_DELIVERY_BACK =
        "Expected DELIVERY after switching back"
    const val FAKE_REST_ID_R1               = "r1"
    const val FAKE_REST_MEGHANA             = "Meghana Foods"
    const val FAKE_REST_RATING_4_6          = 4.6
    const val FAKE_REST_RATING_TEXT_EX      = "Excellent"
    const val FAKE_REST_RATING_COLOR        = "#3F7E00"
    const val FAKE_REST_TOTAL_VOTES_12500   = 12500
    const val FAKE_REST_DELIVERY_TIME_30    = 30
    const val FAKE_REST_DELIVERY_FEE_FREE   = 0.0
    const val FAKE_REST_MIN_ORDER_100       = 100
    const val FAKE_REST_ADDRESS_KORA        = "Koramangala, Bengaluru"
    const val FAKE_REST_LOCALITY_KORA       = "Koramangala"
    const val FAKE_REST_DISTANCE_KM_2_5     = 2.5
    const val FAKE_REST_COST_FOR_TWO_400    = 400
    const val FAKE_REST_OPENING_HOURS       = "11 AM - 11 PM"
    const val FAKE_REST_OFFER_20_OFF        = "20% off above ₹499"
    const val FAKE_REST_CUISINE_BIRYANI     = "Biryani"
    const val FAKE_REST_CUISINE_SOUTH_IND   = "South Indian"
    const val FAKE_REST_RESTAURANT_ID       = "r1"
    const val FAKE_MENU_ID_M1               = "m1"
    const val FAKE_MENU_ID_M2               = "m2"
    const val FAKE_MENU_ID_M3               = "m3"
    const val FAKE_MENU_ID_M4               = "m4"
    const val FAKE_MENU_CHICK_BIR           = "Chicken Biryani"
    const val FAKE_MENU_MUTTON_BIR          = "Mutton Biryani"
    const val FAKE_MENU_CHICK_65            = "Chicken 65"
    const val FAKE_MENU_PANEER_TIKKA        = "Paneer Tikka"
    const val FAKE_MENU_PRICE_249           = 249.0
    const val FAKE_MENU_PRICE_349           = 349.0
    const val FAKE_MENU_PRICE_199           = 199.0
    const val FAKE_MENU_PRICE_179           = 179.0
    const val FAKE_MENU_PRICE_100           = 100.0
    const val FAKE_MENU_CATEGORY_BIRYANI    = "Biryani"
    const val FAKE_MENU_CATEGORY_STARTERS   = "Starters"
    const val FAKE_MENU_CATEGORY_TEST       = "Test"
    const val FAKE_MENU_DESC_PREFIX         = "Delicious "
    const val FAKE_ERROR_SOMETHING_WRONG    = "Something went wrong"
    const val FAKE_CART_ID_PREFIX           = "fake_"
    const val FAKE_CART_MENU_ID_PREFIX      = "m"
    const val FAKE_CART_ITEM_NAME_PREFIX    = "Item "
    const val FAKE_CART_RESTAURANT_ID       = "r1"
    const val FAKE_USER_ID_U1               = "u1"
    const val FAKE_USER_NAME_TEST           = "Test"
    const val FAKE_USER_EMAIL_EMPTY         = ""
    const val FAKE_USER_PHONE               = "9876543210"
    const val FAKE_ERR_NOT_IMPLEMENTED      = "Not implemented"
    const val CART_BADGE_ONE                = "1"
    const val CART_BADGE_THREE              = "3"

}